# This is a config for E2B sandbox template.
# You can use template ID (l5lhs6628331warwljws) or template name (your-project-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("your-project-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("your-project-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('your-project-nextjs-test')

team_id = "eb0e6f98-6fc4-46ff-bce7-7987fb54c4cd"
start_cmd = "/compile_page.sh"
dockerfile = "E2B.dockerfile"
template_name = "your-project-nextjs-test"
template_id = "l5lhs6628331warwljws"
